config/routes.rb
Rails.application.routes.draw do
  get 'welcome/tables'
  get 'welcome/diagram'
  get 'error', to: 'error#index'

  resources :rangkings
  resources :kriteria
  resources :alternatifs
  root to: 'welcome#diagram'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  require 'matrix'
  before_action :cekData

  def error
  end

  def tables

    @alternatif = getAllAlternatifs
    @kriteria = getAllKriterias
    @rangking = getAllRangkings



    @rangeAlternatif = countRangeAlternatif
    @rangeKriteria = countRangeKriteria
    @X = getX
    @R = getR
    @Y = getY
    @APlus = getAPlus
    @AMinus = getAMinus
  end

  def diagram
    @rangeKriteria = countRangeKriteria
    @rangking = getAllRangkings
    @alternatif = getAllAlternatifs
    @rangeAlternatif = countRangeAlternatif
    @DPlus = getDPlus
    @DMinus = getDMinus
    @V = getV
    @data = getResult
  end


  private

    def cekData
      if Alternatif.first == nil or Kriterium.first == nil or Rangking.first == nil then
          redirect_to error_path
      end
    end
    def getRangkingByKriteriaId(id)
      return Rangking.where(kriteria_id: id)
    end

    def getAllKriterias
      return Kriterium.all
    end

    def getAllRangkings
      return Rangking.all
    end

    def getAllAlternatifs
      return Alternatif.all
    end

    def getX
      @Xtemp=[]
      i=0
      @kriteria = getAllKriterias
      @kriteria.each do |k|
        x=0
        @rang = getRangkingByKriteriaId(k.id)
          @rang.each do |r|
            x=x+(r.nilai.to_f ** 2)
          end
        @Xtemp[i] = Math.sqrt(x)
        i+=1
      end
      return @Xtemp
    end

    def getR
      @Rtemp=[]
      n=0
      @kriteria = getAllKriterias
      @kriteria.each do |k|
        @r=[]
        i=0
        @rang = getRangkingByKriteriaId(k.id)
        @rang.each do |r|
          @r[i] = r.nilai.to_f / getX[n]
          i+=1
        end
        @Rtemp[n] = @r
        n+=1
      end
      return @Rtemp
    end

    def getMatrixR
      @matrix = Matrix[]
      n=0
      @X = getX
      @kriteria = getAllKriterias
      @kriteria.each do |k|
        @r=[]
        i=0
        @rang = getRangkingByKriteriaId(k.id)
        @rang.each do |r|
          @r[i] = r.nilai.to_f / @R[n]
          i+=1
        end
        @matrix = Matrix.rows(@matrix.to_a << @r)
        n+=1
      end
      return @matrix
    end

    def getY
      @Ytemp=[]
      @X = getX
      n=0
      @kriteria = getAllKriterias
      @kriteria.each do |k|
        @r=[]
        i=0
        @rang = getRangkingByKriteriaId(k.id)
        @rang.each do |r|
          @r[i] = (r.nilai.to_f / @X[n])*k.bobot.to_f
          i+=1
        end
        @Ytemp[n] = @r
        n+=1
      end
      return @Ytemp
    end

    def getAPlus
      j=0
      @AP = []
      @kr = getAllKriterias.first;
      @Y = getY
      @Y.each do |subY|
          @A=nil
          subY.each do |y|
            case @kr.tipe
            when 0
              begin
                if y < @A
                  @A=y
                end
              rescue
                @A=y
              end
            when 1
              begin
                if y > @A
                  @A=y
                end
              rescue
                @A=y
              end
            end
          end
          @AP[j]=@A
          j+=1
          @kr = @kr.next
      end
      return @AP
    end

    def getAMinus
      j=0
      @AP = []
      @kr = getAllKriterias.first;
      getY.each do |subY|
          @A=nil
          subY.each do |y|
            case @kr.tipe
            when 0
              begin
                if y > @A
                  @A=y
                end
              rescue
                @A=y
              end
            when 1
              begin
                if y < @A
                  @A=y
                end
              rescue
                @A=y
              end
            end
          end
          @AP[j]=@A
        j+=1
        @kr = @kr.next
      end
      return @AP
    end


    def getDPlus
      i=0
      @AP = getAPlus
      @DP=[]
      @Y = getY
      countRangeAlternatif.each do |a|
        @D=0
        j=0
        countRangeKriteria.each do |k|
          begin
            @D += (@Y[j][i]-@AP[j]) ** 2
            j+=1
          rescue
            @D += 0
            j+=1
          end

        end
        @DP[i]= Math.sqrt(@D)
        i+=1
      end
      return @DP
    end

    def getDMinus
      i=0
      @AM = getAMinus
      @DP=[]
      @Y = getY
      countRangeAlternatif.each do |a|
        @D=0
        j=0
        countRangeKriteria.each do |k|
          begin
            @D += (@AM[j]-@Y[j][i]) ** 2
            j+=1
          rescue
            @D += 0
            j+=1
          end

        end
        @DP[i]= Math.sqrt(@D)
        i+=1
      end
      return @DP
    end

    def getV
      @V =[]
      @DM = getDMinus
      @DP = getDPlus
      i=0
      countRangeAlternatif.each do |a|
        @V[i] = @DM[i]/(@DM[i]+@DP[i])
        i+=1
      end
      return @V
    end

    def getDebugD
      i=0
      @DP=[]
      getAllAlternatifs.each do |a|
        @D=[]
        j=0
        getAllKriterias.each do |k|
            @D[j]= (getY[j][i]-getAPlus[j]) ** 2
            j+=1
        end
        @DP[i]= @D
        i+=1
      end
      return @DP
    end

    def countRangeAlternatif
      return (0..getAllAlternatifs.size-1)
    end

    def countRangeKriteria
      return (0..getAllKriterias.size-1)
    end

    def getResult
      @data = []
      @V = getV
      i=0
      @alternatif = getAllAlternatifs

      @alternatif.each do |al|
        @data[i] = Hasil.new(al.nama_alternatif, @V[i])
        i+=1
      end

      return @data
    end
  end

  class Hasil
    def initialize(n , v)
      @nama=n
      @v = v
    end

    def getNama
      return @nama
    end

    def getVR
      return @v
    end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/diagram.html.erb
<section class="content-header">
  <h1>
    Diagram
    <small>Keputusan</small>
  </h1>
</section>
<% ra = @rangeAlternatif %>
<% rk = @rangeKriteria %>
<!-- Main content -->

<section class="content">
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-aqua">
        <div class="inner">
          <h3><%= ra.count %></h3>

          <p>Alternatif</p>
        </div>
        <a href="<%= alternatifs_url %>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-green">
        <div class="inner">
          <h3><%= rk.count %></h3>

          <p>Kriteria</p>
        </div>
        <a href="<%= kriteria_url %>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-yellow">
        <div class="inner">
          <h3><%= @rangking.count %></h3>

          <p>Perangkingan</p>
        </div>
        <a href="<%= rangkings_url %>" class="small-box-footer">Lihat <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
      <!-- small box -->
      <div class="small-box bg-red">
        <div class="inner">
          <% begin %>
          <h3><%= @alternatif[@V.each_with_index.max[1]].nama_alternatif %></h3>
          <% rescue %>
          <h3>Belum ada</h3>
          <% end %>
          <p>Alternatif Terbaik</p>
        </div>
        <a href="<%= welcome_tables_url %>" class="small-box-footer">Analisis <i class="fa fa-arrow-circle-right"></i></a>
      </div>
    </div>
    <!-- ./col -->
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-body">
          <div class="row">
            <div class="col-md-8">
              <p class="text-center">
                <strong>Alternatif</strong>
              </p>

              <div class="chart">
                <!-- Sales Chart Canvas -->
                  <%= line_chart @data.map{|i| [i.getNama, i.getVR]}, discrete: true %>
              </div>
              <!-- /.chart-responsive -->
            </div>
            <!-- /.col -->
          </div>
        </div>
      </div>
    </div>
  </div>
    <!-- /.row -->
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Tabel Ideal</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
              <thead>
                <td><center><b>#</b></center></td>
                <th scope="col">D (+)</th>
                <th scope="col">D (-)</th>
                <th scope="col">V</th>
              </thead>
              <tbody>
                <% alt = 0 %>
                <% ra.each do |al| %>
                  <tr>
                    <th scope="col">A <%= alt+1 %></th>
                    <td><%= @DPlus[alt].round(3) %></td>
                    <td><%= @DMinus[alt].round(3) %></td>
                    <td><b><%= @V[alt].round(3) %></b></td>
                  </tr>
                <% alt += 1 %>
                <% end %>
              </tbody>
            </table>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
    </div>
  <!-- ./box-body -->
</section>

app/views/welcome/tables.html.erb
<section class="content-header">
  <h1>Tabel
  <small>Analisis</small>
  </h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Tabel Rangking Alternatif</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
              <thead>
                <tr>
                  <td><center><b>#</b></center></td>
                  <% kr = 1 %>
                  <% @kriteria.each do |k| %>
                  <% tipe = case k.tipe %>
                    <% when 1 then "B" %>
                    <% when 0 then "C" %>
                    <% end %>
                  <th scope="col"><%= kr.to_s+" "+tipe %></th>
                  <% kr=kr+1 %>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <% @alternatif.each do |a| %>
                <tr>
                <th scope="row"><%= a.nama_alternatif %></th>
                <% data = Rangking.where(alternatif_id: a.id) %>
                      <% data.each do |d| %>
                        <td ><%= d.nilai.round(3) %></td>
                      <% end %>
                </tr>
                <% end %>
                <tr>
                <th scope="row"> |X| </th>
                      <% @X.each do |x| %>
                        <td ><%= x.round(3) %></td>
                      <% end %>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Matriks R</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
              <tbody>
                <% j=0 %>
                <% @rangeAlternatif.each do |a| %>
                    <tr>
                      <% i=0 %>
                      <% @R.each do |subAr| %>
                        <td><%= @R[i][j].round(3) %></td>
                        <% i+=1 %>
                      <% end %>
                    </tr>
                  <% j+=1 %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Matriks Y</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
              <tbody>
                <% j=0 %>
                <% @rangeAlternatif.each do |a| %>
                    <tr>
                      <% i=0 %>
                      <% @Y.each do |subAr| %>
                        <td><%= @Y[i][j].round(3) %></td>
                        <% i+=1 %>
                      <% end %>
                    </tr>
                  <% j+=1 %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Nilai A</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
              <tbody>
                <tr>
                  <th scope="col">A+</th>
                  <% @APlus.each do |ap| %>
                    <td><%= ap.round(3) %></td>
                  <% end %>
                </tr>
                <tr>
                  <th scope="col">A-</th>
                  <% @AMinus.each do |am| %>
                    <td><%= am.round(3) %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</section>